dist: xenial

language: node_js
node_js:
  - "7"

install:
  - npm install
  - npm run build

script:
  - true # no test suite right now :-(

cache: npm

before_deploy:
  - rm dist/.gitignore dist/combined.js
  - ls -l dist # temp debug

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
